# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 16:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jasmin_services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinJISCMailListBehaviour",
            fields=[
                (
                    "behaviour_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="jasmin_services.Behaviour",
                    ),
                ),
                (
                    "list_name",
                    models.CharField(
                        help_text="The name of the JISCMail mailing list to join",
                        max_length=100,
                    ),
                ),
                (
                    "joined_users",
                    models.ManyToManyField(
                        blank=True, editable=False, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Join JISCMail List Behaviour",
            },
            bases=("jasmin_services.behaviour",),
        ),
        migrations.RemoveField(
            model_name="notifyoncebehaviour",
            name="behaviour_ptr",
        ),
        migrations.RemoveField(
            model_name="notifyoncebehaviour",
            name="notification_type",
        ),
        migrations.DeleteModel(
            name="NotifyOnceBehaviour",
        ),
    ]
