# Generated by Django 2.2.4 on 2020-08-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='auto_accept',
            field=models.BooleanField(default=False, help_text='Auto accepts all requested access giving users with a 1 year experation date '),
        ),
    ]
