# Generated by Django 2.2.4 on 2020-09-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_services', '0002_role_auto_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='approver_message',
            field=models.TextField(blank=True, default='', help_text='Service specific instructions to be added to the external approver message.', null=True),
        ),
    ]
