# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import jasmin_ldap_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_services', '0004_migrate_ldap_group_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapgroupbehaviour',
            name='group_dn',
        ),
    ]
