# Generated by Django 2.2.5 on 2019-09-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jasmin_services", "0009_migrate_deputy_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinjiscmaillistbehaviour",
            name="list_name",
            field=models.CharField(
                help_text="The name of the JISCMail mailing list to join",
                max_length=100,
                unique=True,
            ),
        ),
    ]
