# Generated by Django 2.2.9 on 2021-04-01 08:56

import django.core.validators
from django.db import migrations, models
import jasmin_ldap_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_services', '0010_auto_20190916_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='incomplete',
            field=models.BooleanField(default=False),
        ),
    ]
