# Generated by Django 2.2.9 on 2021-02-24 10:00

import django.core.validators
from django.db import migrations, models
import jasmin_ldap_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_services', '0010_auto_20190916_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='object_store_url',
            field=models.CharField(blank=True, default='', help_text='URL for object store. Leave blank if service is not an object store. ', max_length=250),
        ),
    ]
