# Generated by Django 2.2.9 on 2021-03-08 09:36

import django.core.validators
from django.db import migrations
import jasmin_ldap_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_services', '0010_auto_20190916_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('category__position', 'category__long_name', 'position', 'name'), 'permissions': (('create_group_role', 'Can great a new group'),)},
        ),
    ]
