# Generated by Django 2.2.24 on 2021-11-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_services', '0011_auto_20210317_0804'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['position', 'long_name'], name='jasmin_serv_positio_fd6e81_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['position', 'name'], name='jasmin_serv_positio_95ece6_idx'),
        ),
    ]
