# Generated by Django 2.2.9 on 2021-11-08 13:30

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jasmin_services", "0011_auto_20210317_0804"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="auto_accept",
            field=models.BooleanField(
                default=False,
                help_text="Auto accepts all requested access giving users with a 1 year experation date ",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="approver_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Service specific instructions to be added to the external approver message.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="instution_countries",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Coutries a user's institute must be located to begin approval. Hold ctrl or cmd for mac to select multiple countries. Leave blank for any country.",
                max_length=746,
                multiple=True,
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["position", "long_name"], name="jasmin_serv_positio_fd6e81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["position", "name"], name="jasmin_serv_positio_95ece6_idx"
            ),
        ),
    ]
