# Generated by Django 2.2.24 on 2021-11-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jasmin_services", "0012_auto_20211108_1329"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(
                fields=["role", "user", "granted_at"],
                name="jasmin_serv_role_id_f8ad17_idx",
            ),
        ),
    ]
