# Generated by Django 2.2.4 on 2020-10-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_services', '0013_new_grant_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='role',
        ),
		migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.RemoveField(
            model_name='request',
            name='grant',
        ),
        migrations.DeleteModel(
            name='Grant',
        ),
		migrations.RenameModel('Grant_new','Grant'),
    ]
