# Generated by Django 2.2.9 on 2021-11-08 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jasmin_services", "0014_new_grant_migrate_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="request",
            options={
                "get_latest_by": "requested_at",
                "ordering": (
                    "access__role__service__category__position",
                    "access__role__service__category__long_name",
                    "access__role__service__position",
                    "access__role__service__name",
                    "access__role__position",
                    "access__role__name",
                    "-requested_at",
                ),
                "permissions": (("decide_request", "Can make decisions on requests"),),
            },
        ),
        migrations.RemoveField(
            model_name="request",
            name="role",
        ),
        migrations.RemoveField(
            model_name="request",
            name="user",
        ),
        migrations.RemoveField(
            model_name="request",
            name="grant",
        ),
        migrations.DeleteModel(
            name="Grant",
        ),
        migrations.RenameModel("Grant_new", "Grant"),
    ]
