# Generated by Django 2.2.4 on 2021-02-18 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_services', '0015_auto_20201019_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'ordering': ('role__service__category__position', 'role__service__category__long_name', 'role__service__position', 'role__service__name', 'role__position', 'role__name'), 'verbose_name_plural': 'accesses'},
        ),
    ]
