# Generated by Django 2.2.9 on 2021-11-08 14:02

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_services', '0015_new_grant_deletions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='access',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, related_name='requests', related_query_name='request', to='jasmin_services.Access'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
