# Generated by Django 2.2.18 on 2021-06-14 14:52

import django.core.validators
from django.db import migrations, models
import jasmin_ldap_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('jasmin_services', '0016_auto_20210218_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='incomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='ceda_managed',
            field=models.BooleanField(default=False, help_text='Whether the service is managed by CEDA.'),
        ),
    ]
