# Generated by Django 3.2.13 on 2022-09-14 08:52

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jasmin_services", "0020_service_disabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeycloakAttributeBehaviour",
            fields=[
                (
                    "behaviour_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="jasmin_services.behaviour",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("jasmin_services.behaviour",),
        ),
        migrations.AlterField(
            model_name="service",
            name="instution_countries",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Coutries a user's institute must be located to begin approval. Hold ctrl or cmd for mac to select multiple countries. Leave blank for any country.",
                max_length=746,
                multiple=True,
            ),
        ),
    ]
