# Generated by Django 5.0.7 on 2024-07-29 14:40

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jasmin_services", "0024_grant_revoked_at_alter_behaviour_polymorphic_ctype"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="internal_comment",
            field=models.TextField(blank=True, verbose_name="Internal nodes"),
        ),
        migrations.AddField(
            model_name="request",
            name="internal_comment",
            field=models.TextField(blank=True, verbose_name="Internal nodes"),
        ),
    ]
