# Generated by Django 5.1.5 on 2025-02-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jasmin_services", "0025_add_internal_comment_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="internal_comment",
            field=models.TextField(blank=True, verbose_name="Internal notes"),
        ),
    ]
