# Generated by Django 5.1.5 on 2025-02-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jasmin_services", "0027_request_jasmin_serv_state_25f7c6_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["ceda_managed"], name="jasmin_serv_ceda_ma_c2ebfe_idx"),
        ),
    ]
