# Generated by Django 5.1.5 on 2025-02-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jasmin_services", "0028_service_jasmin_serv_ceda_ma_c2ebfe_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="request",
            index=models.Index(fields=["resulting_grant"], name="jasmin_serv_resulti_2f6892_idx"),
        ),
        migrations.AddIndex(
            model_name="request",
            index=models.Index(
                fields=["state", "resulting_grant"], name="jasmin_serv_state_36e4c3_idx"
            ),
        ),
    ]
