# Generated by Django 5.2.13 on 2026-04-16 11:21

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jasmin_services", "0029_request_jasmin_serv_resulti_2f6892_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="require_role_to_apply",
            field=models.ForeignKey(
                default=None,
                help_text="Require uses have this role before they are able to apply for roles in this category.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jasmin_services.role",
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="internal_comment",
            field=models.TextField(blank=True, verbose_name="Internal notes"),
        ),
        migrations.AlterField(
            model_name="role",
            name="auto_accept",
            field=models.BooleanField(
                default=False,
                help_text="Auto accepts all requested access giving users with a 1 year expiration date.",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="institution_countries",
            field=django_countries.fields.CountryField(
                blank=True,
                help_text="Coutries a user's institute must be located to begin approval. Hold ctrl or cmd for mac to select multiple countries. Leave blank for any country.",
                max_length=746,
                multiple=True,
            ),
        ),
    ]
