# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jasmin_metadata", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ipv4field",
            name="require_reverse_dns_lookup",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="field",
            name="help_text",
            field=models.TextField(
                blank=True,
                help_text="Help text for the field. Markdown syntax is permitted.",
            ),
        ),
    ]
